### ISSUE TITLE
Documentation for how to run the test suite

### ISSUE THREAD

**Issue by steppi** [BPSB/combine-p-values-discrete#2]
It would be nice to document how to run the test suite. I was able to piece it together from  [.github/workflows/test.yml](https://github.com/BPSB/combine-p-values-discrete/blob/2b35d5957ea8a816569305ac8a5edf52ab4d1adb/.github/workflows/test.yml#L16-L23). It seems that the preferred command is `pytest -c tests/pytest.ini` with options  `pytest -c tests/pytest.ini -m not slow` to run only tests not marked slow, and `pytest -c tests/pytest.ini -m slow` to run only the slow tests. As an aside, I think the `-c` option is for specifying a config file with non-default name. Was having this a quirk to get things working correctly on CI?

I see in`test.yml` and also [setup.py](https://github.com/BPSB/combine-p-values-discrete/blob/master/setup.cfg) that the test requirements are `pytest`, `statsmodels`, and `pytest-rng`. I found it a little odd that `statsmodels` is in the [requirements.txt](https://github.com/BPSB/combine-p-values-discrete/commit/8726d247bd3badaeb67f595a6392a3ff30ec16b6) because it's required for testing but the other test requirements were not. If you replace

```python
tests_require = ["pytest","statsmodels","pytest-rng"],
```

with 
```python
extras_require={'test': ['pytest', 'statsmodels', 'pytest-rng']},
```

then someone could just install the test dependencies with `pip install .[test]`. This would be more convenient for the user, and also not require updating the documentation if the test requirements change.

**Comment by Wrzlprmft** [comment]
> It would be nice to document how to run the test suite.

Done. I added it to the read-me.

> I was able to piece it together from [.github/workflows/test.yml](https://github.com/BPSB/combine-p-values-discrete/blob/2b35d5957ea8a816569305ac8a5edf52ab4d1adb/.github/workflows/test.yml#L16-L23). It seems that the preferred command is `pytest -c tests/pytest.ini` with options `pytest -c tests/pytest.ini -m not slow` to run only tests not marked slow, and `pytest -c tests/pytest.ini -m slow` to run only the slow tests.

Correct. Mind that these are used in the CI only this way such that the fast tests are run first.

> As an aside, I think the `-c` option is for specifying a config file with non-default name. Was having this a quirk to get things working correctly on CI?

Correct. In my understanding, `pytest.ini` is the default name for the config file and I do not need to specify it on my system. The CI needed it specified for some reason, however.

> I see in`test.yml` and also [setup.py](https://github.com/BPSB/combine-p-values-discrete/blob/master/setup.cfg) that the test requirements are `pytest`, `statsmodels`, and `pytest-rng`. I found it a little odd that `statsmodels` is in the [requirements.txt](https://github.com/BPSB/combine-p-values-discrete/commit/8726d247bd3badaeb67f595a6392a3ff30ec16b6) because it's required for testing but the other test requirements were not. If you replace […] then someone could just install the test dependencies with `pip install .[test]`. This would be more convenient for the user, and also not require updating the documentation if the test requirements change.

This is based on another attempt to get the CI running, which should not have been permanent, but just a test to see where the issue was. Your suggestion works both in the CI and elsewhere.

**Comment by steppi** [comment]
Looks good. Thanks. I'll go ahead and close this.
